### ISSUE TITLE
about person tracking algorithm for AVA dataset

### ISSUE THREAD

**Issue by Chuckie-He** [chaoyuaw/lvu#1]
Hi, I want to track the person in adjacent frame，and I have detected the person bbox in each keyframe, could you tell me how to track them？I haven't found it in your paper, please help, thank you!

**Comment by Chuckie-He** [comment]
In part 4.3.of the paper(Instance Representations), You have mentioned that you adopted the algorithm described in [AVA: A video dataset of spatio-temporally localized atomic visual actions] to track person. I want to know more details about it, did you train a person reid network and get person embeddings first, and then match them with the Hungarian algorithm? Is it convenient for you to provide the relevant code or finetuned model? Please help, thank you.

**Comment by chaoyuaw** [comment]
Hi @Chuckie-He , Thanks for your question!

I followed https://arxiv.org/pdf/1705.08421v3.pdf and used [37] of the paper for tracking (i.e. https://arxiv.org/pdf/1611.08563.pdf). Thus no additional feature/embedding is required. It only uses IOU + scores.

(Please note that what I just shared is "v3" of the paper, and I just realized that in the latest version they used something else. Sorry for the confusion. )

(I closed this task for now, but please feel free to reopen the task if you have any further questions:) thank you! )

**Comment by Chuckie-He** [comment]
@chaoyuaw thank you for your reply, but in the paper[https://arxiv.org/pdf/1611.08563.pdf](url)，it used the class specific scores for tracking and generated action tubes for each class. do you use detection scores instead?

**Comment by chaoyuaw** [comment]
@Chuckie-He, sorry for the late reply. Yes, I used just detection scores.

**Comment by Chuckie-He** [comment]
@chaoyuaw sorry, I don't understand it. so your way is to select the box which has the highest detection score and IOU is greater than a threshold when matching, but how can you ensure that they are the same instance?

**Comment by chaoyuaw** [comment]
@Chuckie-He, This indeed is a very trivial tracker and it doesn't consider visual similarity between boxes. However, in cases of "movies", this turns out to work okay because for movies, typically the camera is stationary or at least doesn't move fast, so tracking is quite easy --- just matching the box location based on IOU already gives good results. If your videos have more motion, I do think you might want to use a better tracker.
